// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try {
  // @ts-ignore
  await import("dotenv/config");
} catch (e) {
  // dotenv not present, environment variables assumed to be set externally
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
